name = "daro-parser-worker"        # назва вашого Worker
main = "index.js"
type = "javascript"
compatibility_date = "2025-05-16"
workers_dev = true                    # якщо пушити у worker.dev піддомен

# Cron-тригер: 1-го та 15-го числа о 00:00 UTC
[triggers]
crons = ["0 0 1,15 * *"]

[observability.logs]
enabled = true

# Підключення до змінних середовища (секрети)
[env.production]
vars = { GITHUB_FILE_PATH = "data/fond_P720.json" }
