name = "daro-parser-worker"
main = "index.js"
compatibility_date = "2026-02-24"
workers_dev = true

[triggers]
crons = ["0 0 1,15 * *"]

[observability.logs]
enabled = true

[browser]
binding = "BROWSER"

[env.production]
name = "daro-parser-worker"
compatibility_flags = ["nodejs_compat"]
vars = { GITHUB_FILE_PATH = "data/fond_P720.json" }

[env.production.browser]
binding = "BROWSER"